import { jsPDF } from 'jspdf';
import { RecommendedCrop } from '../types/crop';
import { getCropSchedule } from '../data/cropMilestones';

export interface GeneratePdfOptions {
  crop: RecommendedCrop;
  cropName: string;
  language: string;
  farmData?: {
    landAcres?: number | null;
    soilType?: string | null;
    waterSource?: string | null;
    waterCapacity?: string | null;
  };
}

export function generateAndDownloadCropPdf(options: GeneratePdfOptions): void {
  const { crop, cropName, farmData } = options;
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  // 1. Header Banner
  doc.setFillColor(13, 99, 27); // #0D631B Forest Green
  doc.rect(0, 0, pageWidth, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FASAL DISHA (CROP ADVISORY & ACTION PLAN)', pageWidth / 2, 11, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Digital Agriculture Decision Support System | ICAR & CACP Benchmark Standards', pageWidth / 2, 18, { align: 'center' });

  y = 34;

  // 2. Summary Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(248, 250, 248);
  doc.roundedRect(12, y, pageWidth - 24, 38, 3, 3, 'FD');

  doc.setTextColor(13, 99, 27);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(`Recommended Crop: ${crop.crop_name_en || crop.crop_id} (${cropName})`, 16, y + 8);

  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const land = farmData?.landAcres ? `${farmData.landAcres} Acres` : '2.5 Acres';
  const soil = farmData?.soilType || 'Black Soil';
  const water = farmData?.waterSource || 'Well / Tube-well';

  doc.text(`• Farm Area: ${land}`, 16, y + 16);
  doc.text(`• Soil Type: ${soil}`, 75, y + 16);
  doc.text(`• Irrigation: ${water}`, 135, y + 16);

  doc.setFont('helvetica', 'bold');
  const profitStr = `INR ${(crop.expected_net_profit_per_acre_inr || 24500).toLocaleString('en-IN')}`;
  const costStr = `INR ${(crop.total_cost_inr_per_acre || 19400).toLocaleString('en-IN')}`;
  const yieldStr = `${crop.expected_yield_qtl_per_acre || 9.5} Quintal / Acre`;

  doc.setTextColor(13, 99, 27);
  doc.text(`• Expected Net Profit: ${profitStr} / Acre`, 16, y + 25);
  doc.setTextColor(70, 70, 70);
  doc.text(`• Total Cost: ${costStr} / Acre`, 16, y + 32);
  doc.text(`• Expected Yield: ${yieldStr}`, 105, y + 32);

  y += 46;

  // 3. 120-Day Action Schedule Table Header
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('120-Day Step-by-Step Agronomic Milestones', 14, y);
  y += 5;

  const schedule = getCropSchedule(crop.crop_id || 'SOYBEAN');
  const milestones = schedule.milestones || [];

  // Table Columns
  doc.setFillColor(235, 243, 235);
  doc.rect(12, y, pageWidth - 24, 7, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(13, 99, 27);
  doc.text('Day', 16, y + 5);
  doc.text('Stage / Activity', 36, y + 5);
  doc.text('Recommended Actions & Advisory Guidance', 85, y + 5);

  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);

  milestones.forEach((m, idx) => {
    if (y > 265) {
      doc.addPage();
      y = 16;
    }

    const rowBg = idx % 2 === 0 ? 255 : 250;
    doc.setFillColor(rowBg, rowBg, rowBg);
    doc.rect(12, y, pageWidth - 24, 11, 'F');
    doc.setDrawColor(230, 230, 230);
    doc.line(12, y + 11, pageWidth - 12, y + 11);

    doc.setTextColor(13, 99, 27);
    doc.setFont('helvetica', 'bold');
    doc.text(`Day ${m.day}`, 16, y + 7);

    doc.setTextColor(30, 30, 30);
    const stageText = m.badge.hi || m.badge.en || 'Stage';
    doc.text(stageText.slice(0, 24), 36, y + 7);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(70, 70, 70);
    const actionText = `${m.title.hi || m.title.en}: ${m.desc.hi || m.desc.en}`;
    const truncatedAction = actionText.length > 70 ? actionText.slice(0, 68) + '...' : actionText;
    doc.text(truncatedAction, 85, y + 7);

    y += 11;
  });

  // 4. Footer
  y = Math.max(y + 8, 270);
  if (y > 280) {
    doc.addPage();
    y = 270;
  }
  doc.setDrawColor(200, 200, 200);
  doc.line(12, y, pageWidth - 12, y);

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'bold');
  doc.text('Kisan Call Centre Toll-Free (24x7): 1800-180-1551', pageWidth / 2, y + 5, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Fasal-Disha Digital Advisory Platform. Based on ICAR package of practices.', pageWidth / 2, y + 9, { align: 'center' });

  // 5. Trigger Immediate File Download
  const filename = `Fasal_Disha_Action_Plan_${crop.crop_id || 'Report'}.pdf`;
  doc.save(filename);
}
